### ISSUE TITLE
Meta: update Assembly Line interviews to move information from `interview_metadata` to `metadata` to support new courtformsonline.org

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#693]
- [ ] Make sure `allowed_courts` is defined correctly
- [ ] Make sure custom error action points to the correct URL for the original PDF
- [ ] Check for any other references to `interview_metadata`
- [ ] Make sure we have all of the new information we want to go on CourtFormsOnline.
